"""
Idempotency service.

Every money-moving mutation must call `execute_idempotent` with a stable
`idempotency_key` (e.g. UUIDv4 generated by the client). On replay with
the same key, the original response is returned without re-posting.
"""
from __future__ import annotations

import hashlib
import json
from datetime import datetime, timedelta
from typing import Any, Awaitable, Callable, Optional

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from ..database.pg_accounting_models import TransactionIdempotency


def request_hash(payload: Any) -> str:
    canon = json.dumps(payload, sort_keys=True, separators=(",", ":"), default=str)
    return hashlib.sha256(canon.encode()).hexdigest()


async def fetch_cached(
    db: AsyncSession, idempotency_key: str
) -> Optional[dict]:
    result = await db.execute(
        select(TransactionIdempotency).filter_by(idempotency_key=idempotency_key)
    )
    rec = result.scalar_one_or_none()
    if rec is None:
        return None
    if rec.expires_at < datetime.utcnow():
        return None
    return {
        "idempotency_key": rec.idempotency_key,
        "status_code": rec.status_code,
        "response_json": json.loads(rec.response_json)
        if rec.response_json
        else None,
        "journal_entry_id": rec.journal_entry_id,
        "cached": True,
    }


async def save_cached(
    db: AsyncSession,
    *,
    idempotency_key: str,
    request_hash_value: str,
    response: Any,
    status_code: int = 200,
    journal_entry_id: Optional[int] = None,
    ttl_hours: int = 24,
) -> None:
    db.add(
        TransactionIdempotency(
            idempotency_key=idempotency_key,
            request_hash=request_hash_value,
            response_json=json.dumps(response, default=str),
            status_code=status_code,
            journal_entry_id=journal_entry_id,
            expires_at=datetime.utcnow() + timedelta(hours=ttl_hours),
        )
    )


async def execute_idempotent(
    db: AsyncSession,
    *,
    idempotency_key: str,
    request_payload: Any,
    handler: Callable[[], Awaitable[Any]],
    journal_entry_id: Optional[int] = None,
) -> Any:
    """
    Run `handler` exactly once per `idempotency_key`. Replays return the
    cached response. The handler is expected to perform its DB work and
    return a JSON-serializable response.
    """
    cached = await fetch_cached(db, idempotency_key)
    if cached is not None:
        return cached["response_json"]

    rh = request_hash(request_payload)
    response = await handler()
    await save_cached(
        db,
        idempotency_key=idempotency_key,
        request_hash_value=rh,
        response=response,
        journal_entry_id=journal_entry_id,
    )
    return response
